input.onButtonPressed(Button.A, function () {
    kitronik_servo_lite.driveForwards(100)
    basic.pause(500)
    kitronik_servo_lite.turnRight(90)
    basic.pause(500)
    kitronik_servo_lite.driveForwards(100)
    basic.pause(500)
    kitronik_servo_lite.turnRight(90)
    basic.pause(500)
    kitronik_servo_lite.driveForwards(100)
    basic.pause(500)
    kitronik_servo_lite.turnRight(90)
    basic.pause(500)
    kitronik_servo_lite.driveForwards(100)
})
kitronik_servo_lite.setDegreesPerSecond(330)
kitronik_servo_lite.setDistancePerSecond(193)
